### ISSUE TITLE
Is there a way to manually add DLC or games without the manager deleting it?

### ISSUE THREAD

**Issue by handicast** [BlueAmulet/GreenLuma-2020-Manager#10]
I want to add some of the unobtainable payday 2 dlcs but every i add it to Applist, and run greenluma it ends up just deleting that file. I can't use normal greenluma cause it keeps on saying "CreateProcess error" so i have to rely on this. Please help

**Comment by BlueAmulet** [comment]
The manager's profiles are stored in `%localappdata%\GLR_Manager\Profiles`, you can add the extra DLCs to the list there
