### ISSUE TITLE
INTERNAL ERROR: cannot create temporary directory!

### ISSUE THREAD

**Issue by DatManRandom** [BlueAmulet/GreenLuma-2020-Manager#15]
I am trying to use GreenLuma to bypass the steam family share limit but I am on macOS while using CrossOver (a program that runs most windows programs on a Mac), when I try to run the exe file the error message below comes up and nothing else happens.
> INTERNAL ERROR: cannot create temporary directory!

Please let me know if you need any more info.

**Comment by BlueAmulet** [comment]
I have zero idea if the manager or GreenLuma itself will work on macOS via wine, but the latest release has been rebuilt with a newer version of PyInstaller that should fix this issue, redownload.
