### ISSUE TITLE
Can't find some AppIDs

### ISSUE THREAD

**Issue by FlashMau5** [BlueAmulet/GreenLuma-2020-Manager#16]
Hi, there is one big problem here, i used to solve it modifying the JSON file into the AppData folder, but now this workaround doesn't work anymore.
Some AppIDs are not in store anymore or they're hidden, to fix that the easiest method i think is to add a way to write the AppID manually (of the missing IDs on steam) and store their value into JSON file.

**Comment by BlueAmulet** [comment]
The manager's profiles are stored in `%localappdata%\GLR_Manager\Profiles`, you can add the hidden AppIDs to the json profiles there.

**Comment by FlashMau5** [comment]
No, i tried, i can't anymore from latest version, it seems to have a backup copy of file (before hidden AppIDs added) when i open the Manager, i can't see them and if i click on Generate the json file will be overwritten.

**Comment by BlueAmulet** [comment]
Can't reproduce
![2022-03-02_121614](https://user-images.githubusercontent.com/43395286/156432911-12002cf1-611e-415a-8ecc-f621e8fe3e74.png)
![2022-03-02_121633](https://user-images.githubusercontent.com/43395286/156432926-4329c330-f8be-4069-a189-2fe7ffeb6e6c.png)
![2022-03-02_121656](https://user-images.githubusercontent.com/43395286/156432935-1376de2f-6b24-4558-ad95-0cfad643cda7.png)

**Comment by FlashMau5** [comment]
Ok, I understand what the problem was, before modify the json file i created a backup in same folder and called it "default.json.bak" or "default.bak" and Greenluma Manager load it instead of the "default.json" file.
