### ISSUE TITLE
Can’t get steam games

### ISSUE THREAD

**Issue by Xerrago** [BlueAmulet/GreenLuma-2020-Manager#17]
I’m able to get any dlc i want but when i try and get a game it just doesn’t show them in my library, do i need the game files or anything or am i just not able to, also when i get the dlc’s it shows in my library but then not in game and when i go to the store it doesn’t say in library.

**Comment by BlueAmulet** [comment]
Steam is not going to just give you games and dlcs (if they have separate files) for free, you still need a source for them. That can be family sharing with someone who owns the game, or just downloading the game files yourself.
