### ISSUE TITLE
Game Not Working

### ISSUE THREAD

**Issue by Xerrago** [BlueAmulet/GreenLuma-2020-Manager#18]
I got the files of the game Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles off of cs.rin.ru and when i try to load the game it shows it in my library but when i start the game it says "Sorry something went wrong. For solutions please visit:" then gives me the support page to create a ticket. Should i try and reinstall or is it something i'm doing wrong?

**Comment by BlueAmulet** [comment]
This game has Denuvo.
