### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by yshtola22** [BlueAmulet/GreenLuma-2020-Manager#20]
Run Luma in the manager and it just says failed to inject, normal 8.0

Makes no sense at all, so I don't know what to put here. The thing fails utterly, every time I follow the steps.

**Comment by BlueAmulet** [comment]
"Failed to inject" is a message from GreenLuma itself and not the manager. All I can suggest is make sure you don't have DLLInjector.exe or Steam.exe set to run as admin, make sure you're not using the exe inside GreenLuma's OnlyForX64DedicatedServers folder, and it's recommended to have GreenLuma inside of it's own folder, and not inside of the Steam folder.
