### ISSUE TITLE
Searching function is broken

### ISSUE THREAD

**Issue by Sakimotor** [BlueAmulet/GreenLuma-2020-Manager#3]
![image](https://user-images.githubusercontent.com/20578016/122783900-43e49e80-d2b2-11eb-8868-78791ba72b35.png)

**Comment by jiaaluo** [comment]
Hey! Friend you can use this as an alternative for now.
https://github.com/nadia2436i/GetDLCInfoFromSteamDB2

**Comment by nitrog0d** [comment]
For now you can open the file `%localappdata%/GLR_Manager/config.json` and change `"use_steamdb": true` to `"use_steamdb": false`

**Comment by WeeabooGod** [comment]
SteamDB updated their TOS and their Webpage with CloudFlare. Its also now against TOS (or probably has been this entire time) to scrape the SteamDB webpage. Using jiaaluo's alternative method or nitrog0d's changing of the use of steamdb is probably best.
