### ISSUE TITLE
I used KMSAuto++ and my Green Luma didn't work

### ISSUE THREAD

**Issue by asdzxc708** [BlueAmulet/GreenLuma-2020-Manager#30]
Green Luma can still be used normally before using KMS, but can't be used after cracking Office
why?
[errors.log](https://github.com/BlueAmulet/GreenLuma-2020-Manager/files/9386437/errors.log)

**Comment by BlueAmulet** [comment]
There are no errors in that log, and I need more information than "can't be used"
Is the manager failing some how? Does the run button do nothing? Does steam fail to open? Does steam open but none of the games are changed?

**Comment by asdzxc708** [comment]
No DLC injected
[https://youtu.be/4_TlL8FxtzQ](https://youtu.be/4_TlL8FxtzQ)

**Comment by BlueAmulet** [comment]
There was a Steam update recently that broke GreenLuma, an update for GreenLuma was released that should fix this issue. Please update GreenLuma itself and try again. This is likely not an issue caused by the manager.

**Comment by asdzxc708** [comment]
oh I solved it thanks
