### ISSUE TITLE
GreenLuma seems to run, but no DLC is unlocked

### ISSUE THREAD

**Issue by animalsandsuch** [BlueAmulet/GreenLuma-2020-Manager#31]
GreenLuma restarts Steam and boots into it, but no DLC is unlocked despite it being in the list of DLC to unlock. No errors in log either.

**Comment by BlueAmulet** [comment]
Steam recently updated and broke GreenLuma, an update was released today fixing the issue. Update your GreenLuma and try again. This is not an issue of the manager.

**Comment by LOADOUT32** [comment]
> Steam recently updated and broke GreenLuma, an update for GreenLuma was released today fixing the issue. Update your GreenLuma and try again. This is not an issue of the manager.

There is no Update for GL available.

**Comment by BlueAmulet** [comment]
Oh okay, I guess GreenLuma 2020 1.3.8 wasn't released August 20, 2022 then. 🙄
