### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by Rubacava1** [BlueAmulet/GreenLuma-2020-Manager#32]
i was using greenluma manager like 3 days ago without anny issue but i think after the steam update it stopped working. everything looks normal i launch the program and press run greenluma button, it restarts steam but the games i selected are not unlocked. tried redownloading both the greenluma and greenluma manager but no help. errors.log says nothing too

**Comment by BlueAmulet** [comment]
Steam updates can break GreenLuma and you will have to wait until an update that fixes GreenLuma is made, this is not related to the manager.

**Comment by Rubacava1** [comment]
oh okay thanks for responding
