### ISSUE TITLE
GREENLUMA NOT WORKING

### ISSUE THREAD

**Issue by Splitsecond161** [BlueAmulet/GreenLuma-2020-Manager#35]
As the title said, greenluma not working anymore. I want to know if there's anyone actually make it works again?

**Comment by BlueAmulet** [comment]
Both the manager and greenluma are still working.
You're going to have to be more descriptive than that. What part isn't working? Opening manager? Searching? Adding games? Steam doesn't open? Games aren't unlocked?

**Comment by Splitsecond161** [comment]
the dlc not working, like the dlc aren't unlocked. so i'm curious why you're saying that it is working

**Comment by BlueAmulet** [comment]
Working fine here. Make sure your GreenLuma is up to date, the latest version is GreenLuma 2022 1.3.8
![2022-09-03_230529](https://user-images.githubusercontent.com/43395286/188298332-2c6ff79d-3e27-446d-9005-1ccb4b2ffcc2.png)

**Comment by Splitsecond161** [comment]
my version is 1.3.8.7 and I tried it again, no luck. may i know your steam region?

**Comment by BlueAmulet** [comment]
GreenLuma, not the manager. This isn't a manager problem anyway, the manager doesn't handle the actual unlocking of dlc or games, it just sets up the files that tell GreenLuma itself what to unlock. I've verified that both are working still, so ask for help with GreenLuma on it's official forum post.
